definitions:
  steps:
  - step: &id004
      top_n: 1000 # 10 thin_spheres_elec elec * 10 thin_spheres_desolv desolv * 10 matching_spheres_perturbation
      parameters:
        dock_files_generation: &id002

          thin_spheres_elec:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]
            penetration: 0.0
            distance_to_ligand: 2.0

          thin_spheres_desolv:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
            penetration: 0.0
            distance_to_ligand: 2.0

        dock_files_modification:
          matching_spheres_perturbation:
            use: true
            num_samples_per_matching_spheres_file: 10
            max_deviation_angstroms: 0.4